name: update-gh-activity

on:
  schedule:
    - cron: '30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{secrets.PER_TOKEN}}
